# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39e54e5bfa5acf836d59131379a029fcbddf412dc0e7aee15d9b751563663cd2228646499efa5e574e1b2b0b311e990411b4585ea9628217a3a40b240739c71d

test:
  secret_key_base: a5ad18acd6f7565b7ef174e46e9ba84cab56eac08895ab1a5bb8f9618607141cae1a3f04c717217e7c3636d63c0540626efa85e83bca4f5e971414691544d41d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
